=== arizonamav/Old-paparazzi-designs/paparazzi3ece_old/paparazzi3ece_ross/conf/flight_plans/flight_plan.dtd
<!-- Paparazzi flight plan DTD -->

<!ELEMENT flight_plan (header?, waypoints,include*,exceptions?,blocks)>

<!ELEMENT procedure (param*,waypoints,exceptions?,blocks)>

<!ELEMENT header (#PCDATA)>

<!ELEMENT waypoints (waypoint+)>
<!ELEMENT waypoint EMPTY>

<!ELEMENT exceptions (exception*)>

<!ELEMENT blocks (block+)>
<!ELEMENT block (exception|while|heading|attitude|go|xyz|set|call|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval)*>

<!ELEMENT include (arg|with)*>
<!ELEMENT arg EMPTY>
<!ELEMENT with EMPTY>

<!ELEMENT while (exception|while|heading|attitude|go|xyz|set|call|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval)*>
<!ELEMENT for (exception|while|heading|attitude|go|xyz|set|call|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval)*>
<!ELEMENT exception EMPTY>
<!ELEMENT heading EMPTY>
<!ELEMENT attitude EMPTY>
<!ELEMENT go EMPTY>
<!ELEMENT xyz EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT circle EMPTY>
<!ELEMENT eight EMPTY>
<!ELEMENT oval EMPTY>
<!ELEMENT survey_rectangle EMPTY>
<!ELEMENT deroute EMPTY>
<!ELEMENT stay EMPTY>
<!ELEMENT follow EMPTY>
<!ELEMENT param EMPTY>
<!ELEMENT return EMPTY>


<!ATTLIST flight_plan name CDATA #REQUIRED>
<!ATTLIST flight_plan lat0 CDATA #REQUIRED>
<!ATTLIST flight_plan lon0 CDATA #REQUIRED>
<!ATTLIST flight_plan max_dist_from_home CDATA #REQUIRED>
<!ATTLIST flight_plan qfu CDATA #REQUIRED>
<!ATTLIST flight_plan ground_alt CDATA #REQUIRED>
<!ATTLIST flight_plan security_height CDATA #REQUIRED>
<!ATTLIST flight_plan alt CDATA #REQUIRED>
<!ATTLIST flight_plan ir_square_utmx_min CDATA #IMPLIED>
<!ATTLIST flight_plan ir_square_utmy_max CDATA #IMPLIED>
<!ATTLIST flight_plan ir_square_width CDATA #IMPLIED>
<!ATTLIST flight_plan ir_correct_steps CDATA #IMPLIED>

<!ATTLIST waypoints
utm_x0 CDATA #IMPLIED
utm_y0 CDATA #IMPLIED>

<!ATTLIST waypoint
name CDATA #REQUIRED
x CDATA #REQUIRED
y CDATA #REQUIRED
lat CDATA #IMPLIED
lon CDATA #IMPLIED
alt CDATA #IMPLIED>

<!ATTLIST block 
name CDATA #REQUIRED
strip_button CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST exception
cond CDATA #REQUIRED
deroute CDATA #REQUIRED>

<!ATTLIST while cond CDATA #IMPLIED>

<!ATTLIST for
var CDATA #REQUIRED
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST heading 
course CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
until CDATA #REQUIRED>

<!ATTLIST attitude
roll CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST go 
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
from CDATA #IMPLIED
from_qdr CDATA #IMPLIED
from_dist CDATA #IMPLIED
hmode CDATA #IMPLIED
vmode CDATA #IMPLIED
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
cam_ac_target CDATA #IMPLIED
target CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
approaching_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED>

<!ATTLIST set
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST call
fun CDATA #REQUIRED>

<!ATTLIST follow
ac_id CDATA #REQUIRED
distance CDATA #REQUIRED
height CDATA #REQUIRED
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
target CDATA #IMPLIED
cam_ac_target CDATA #IMPLIED>

<!ATTLIST xyz
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
cam_ac_target CDATA #IMPLIED
target CDATA #IMPLIED
radius CDATA #IMPLIED>

<!ATTLIST circle
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
target CDATA #IMPLIED
cam_ac_target CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST eight
center CDATA #REQUIRED
turn_around CDATA #REQUIRED
radius CDATA #REQUIRED>

<!ATTLIST oval
p1 CDATA #REQUIRED
p2 CDATA #REQUIRED
radius CDATA #REQUIRED>

<!ATTLIST survey_rectangle
grid CDATA #REQUIRED
wp1 CDATA #REQUIRED
wp2 CDATA #REQUIRED>


<!ATTLIST stay
wp CDATA #REQUIRED
vmode CDATA #IMPLIED
throttle CDATA #IMPLIED>

<!ATTLIST deroute
block CDATA #REQUIRED>

<!ATTLIST include
name CDATA #REQUIRED
procedure CDATA #REQUIRED
x CDATA #IMPLIED
y CDATA #IMPLIED
rotate CDATA #IMPLIED>

<!ATTLIST arg
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST with
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST param
name CDATA #REQUIRED
default_value CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST return>

=== arizonamav/Old-paparazzi-designs/paparazzi3ece_old/paparazzi3ece_ross/conf/flight_plans/muret_follow.xml
<!DOCTYPE flight_plan SYSTEM "flight_plan.dtd">

<flight_plan NAME="example - Muret for loops" LON0="1.27289" MAX_DIST_FROM_HOME="1000" GROUND_ALT="185" SECURITY_HEIGHT="25" QFU="270" ALT="250" LAT0="43.46223">

  <waypoints utm_x0="360284.8" utm_y0="4813595.5">
    <waypoint name="HOME" x="0.0" y="30.0" lat="43.4625000078" lon="1.27288231142" alt="250."/>
     </waypoints>

  <blocks>
    <block NAME="home">
       <exception COND="(RcEvent1())" DEROUTE="follow"/>
       <circle wp="HOME" alt="GROUND_ALT+50" radius="-75"/>
    </block>

    <block NAME="follow">
       <exception COND="(RcEvent1())" DEROUTE="home"/>
      <follow ac_id="3" distance="50" height="20"/>
    </block>
  </blocks>
</flight_plan>

=== arizonamav/Old-paparazzi-designs/paparazzi3ece_old/paparazzi3ece_ross/conf/flight_plans/muret_clover.xml
<!DOCTYPE flight_plan SYSTEM "flight_plan.dtd">

<flight_plan NAME="Muret clover" LON0="1.27289" MAX_DIST_FROM_HOME="1000" GROUND_ALT="185" SECURITY_HEIGHT="25" QFU="270" ALT="250" LAT0="43.46223">

  <waypoints utm_x0="360284.8" utm_y0="4813595.5">
    <waypoint name="HOME" x="0.0" y="30.0" lat="43.4625000078" lon="1.27288231142" alt="250."/>
     </waypoints>

     <include name="clover" procedure="clover.xml" x="0" y="0" rotate="0">
     <arg name="rad" value="50"/>
     <with from="event1" to="home"/>
     </include>

  <blocks>
    <block NAME="home">
      <exception COND="(RcEvent1())" DEROUTE="clover.go"/>
      <circle wp="HOME" alt="GROUND_ALT+50" radius="50"/>
    </block>
  </blocks>
</flight_plan>

=== arizonamav/Old-paparazzi-designs/paparazzi3ece_old/paparazzi3ece/conf/flight_plans/IS.xml
<!DOCTYPE flight_plan SYSTEM "flight_plan.dtd">

<flight_plan ground_alt="185" alt="250" lat0="43.4624" lon0="1.2727" max_dist_from_home="500" name="Intelligent Surveillance" qfu="270" security_height="25">
<header>
#include "anemotaxis.h"
#include "chemotaxis.h"
#include "discsurvey.h"
#include "nav_line.h"
#include "bomb.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="0" y="0"/>
    <waypoint name="1" x="-75" y="75"/>
    <waypoint name="2" x="75" y="75"/>
    <waypoint name="MOB" x="200" y="200"/>
    <waypoint name="S1" x="-200" y="-200"/>
    <waypoint name="S2" x="300" y="400"/>
    <waypoint name="C" x="-250" y="-200"/>
    <waypoint name="C1" x="-200" y="-200"/>
    <waypoint name="C2" x="300" y="400"/>
    <waypoint name="PLUME" x="400" y="300"/>
    <waypoint name="BASELEG" x="400" y="300"/>
    <waypoint name="RELEASE" x="400" y="300"/>
    <waypoint name="CLIMB" x="400" y="300"/>
    <waypoint name="TARGET" x="0" y="30" alt="185"/>
    <waypoint name="START" x="200" y="30"/>
  </waypoints>
  <blocks>
<!--
    <block name="wait GPS">
      <while cond="!GpsFixValid()"/>
    </block>

    <block name="init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call fun="NavSetGroundReferenceHere()"/>
      <deroute block="wait"/>
    </block>
-->

    <block name="wait">
      <circle radius="75" wp="1"/>
    </block>

    <block name="eight 1">
      <eight radius="75" center="1" turn_around="2"/>
    </block>

    <block name="Line" strip_button="Line">
         <call fun="nav_line_init()"/>
         <call fun="nav_line(WP_1, WP_2, 75)"/>
    </block>


    <block name="oval" strip_button="Oval">
      <oval p1="1" p2="2" radius="80"/>
    </block>

    <block name="MOB" strip_button="MOB">
      <call fun="NavSetWaypointHere(WP_MOB)"/>
      <circle wp="MOB" radius="100"/>
    </block>

    <block name="Anemotaxis" strip_button="Anem">
      <call fun="nav_anemotaxis_downwind(WP_C, 400)"/>
      <go wp="C" hmode="route" approaching_time="0"/>
      <call fun="nav_anemotaxis_init(WP_C)"/>
      <call fun="nav_anemotaxis(WP_C, WP_C1, WP_C2, WP_PLUME)"/>
    </block>

    <block name="Chemotaxis" strip_button="Chem">
      <call fun="nav_chemotaxis_init(WP_C, WP_PLUME)"/>
      <call fun="nav_chemotaxis(WP_C, WP_PLUME)"/>
    </block>

    <block name="ChemotaxisHere">
      <set var="waypoints[WP_C].x" value="estimator_x"/>
      <set var="waypoints[WP_C].y" value="estimator_y"/>
      <deroute block="Chemotaxis"/>
    </block>

    <block name="Disc survey" strip_button="DS">
      <exception cond="chemo_sensor > 0" deroute="ChemotaxisHere"/>
      <call fun="disc_survey_init()"/>
      <call fun="disc_survey(WP_HOME, 350, 75)"/>
    </block>

    <block name="circle 1 auto pitch">
      <circle radius="75" wp="1" pitch="auto" throttle="0.7"/>
    </block>

    <block name="circle left 1">
      <circle radius="-75" wp="1"/>
    </block>

    <block name="climb 75">
      <circle radius="50+(estimator_z-ground_alt)/2" wp="1" throttle="0.75" pitch="0.3" vmode="throttle" until="10 > PowerVoltage()"/>
    </block>

    <block name="climb 1">
      <circle radius="50+(estimator_z-ground_alt)/2" wp="1" climb="1" pitch="0.1" vmode="climb" until="10 > PowerVoltage()"/>
    </block>

    <block name="descent 0" strip_button="Descent">
      <circle radius="50+(estimator_z-ground_alt)/2" wp="1" throttle="0.0" pitch="-0.3" vmode="throttle" until="ground_alt+50 > estimator_z"/>
      <deroute block="wait"/>
    </block>

    <block name="route12">
      <go approaching_time="0" from="1" hmode="route" wp="2"/>
    </block>

    <block name="glide12">
      <go from="1" hmode="route" vmode="glide" wp="2"/>
    </block>

    <block name="stack 2">
      <circle radius="75" wp="2"/>
    </block>

    <block name="route21">
      <go approaching_time="0" from="2" hmode="route" wp="1"/>
    </block>

    <block name="stack 1">
      <circle radius="75" wp="1"/>
    </block>

    <block name="survey">
      <survey_rectangle grid="150" wp1="S1" wp2="S2"/>
    </block>

    <block name="follow">
      <follow ac_id="5" distance="25" height="10"/>
    </block>

    <block name="bomb" strip_button="Bomb">
      <set value="BombComputeApproach()" var="unit"/>
      <circle radius="BOMB_RADIUS" until="NavQdrCloseTo(DegOfRad(bomb_start_qdr)-10)" wp="BASELEG"/>
    </block>
    <block name="align">
      <exception cond="BombUpdateRelease()" deroute="wait"/>
      <go approaching_time="bomb_trigger_delay" from="START" hmode="route" wp="RELEASE"/>
    </block>
    <block name="shoot">
      <set value="BombShoot()" var="unit"/>
      <go approaching_time="0" from="RELEASE" hmode="route" wp="CLIMB"/>
      <set value="BombCloseHatch()" var="unit"/>
      <deroute block="wait"/>
    </block>
    <block name="close">
      <set value="BombCloseHatch()" var="unit"/>
      <deroute block="wait"/>
    </block>


  </blocks>
</flight_plan>
