=== arizonamav/Old-paparazzi-designs/paparazzi3ece_old/paparazzi3ece_ross/conf/airframes/airframe.dtd
<!-- Paparazzi airframe DTD -->

<!ELEMENT airframe (servos|commands|rc_commands|command_laws|section|makefile)*>
<!ELEMENT servos (servo)*>
<!ELEMENT commands (axis)*>
<!ELEMENT rc_commands (set)*>
<!ELEMENT command_laws (let|set)*>
<!ELEMENT section (define|linear)*>
<!ELEMENT servo EMPTY>
<!ELEMENT axis EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT let EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT linear EMPTY>
<!ELEMENT makefile (#PCDATA)>

<!ATTLIST airframe
name CDATA #IMPLIED>

<!ATTLIST servos>

<!ATTLIST commands>
<!ATTLIST rc_commands>
<!ATTLIST command_laws>

<!ATTLIST section
name CDATA #IMPLIED
prefix CDATA #IMPLIED>

<!ATTLIST servo
name CDATA #REQUIRED
no CDATA #REQUIRED
min CDATA #REQUIRED
neutral CDATA #REQUIRED
max CDATA #REQUIRED>

<!ATTLIST axis
name CDATA #REQUIRED
failsafe_value CDATA #REQUIRED>

<!ATTLIST set
value CDATA #REQUIRED
command CDATA #IMPLIED
servo CDATA #IMPLIED>

<!ATTLIST let
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #REQUIRED
unit CDATA #IMPLIED>

<!ATTLIST linear
name CDATA #REQUIRED
arity CDATA #REQUIRED
coeff1 CDATA #REQUIRED
coeff2 CDATA #IMPLIED
coeff3 CDATA #IMPLIED>

<!ATTLIST makefile
target CDATA #IMPLIED>

=== arizonamav/Old-paparazzi-designs/paparazzi3ece_old/paparazzi3ece/conf/airframes/pogo2.xml
<!DOCTYPE airframe SYSTEM "airframe.dtd">

<airframe name="pogo1">

  <servos>
    <servo name="THR"           no="3" min="1000" neutral="1000" max="2000"/>
    <servo name="AILEVON_RIGHT"  no="0" min="1000" neutral="1595" max="2000"/>
    <servo name="AILEVON_LEFT" no="1" min="1000" neutral="1500" max="2000"/>
    <servo name="RUDDER" no="2" min="2000" neutral="1500" max="1000"/>
  </servos>

  <commands>
    <axis name="THROTTLE" failsafe_value="0"/>
    <axis name="ROLL"     failsafe_value="0"/>
    <axis name="PITCH"    failsafe_value="0"/>
    <axis name="YAW"    failsafe_value="0"/>

  </commands>

  <rc_commands>
    <set command="THROTTLE" value="@THROTTLE"/>
    <set command="ROLL" value="@ROLL"/>
    <set command="PITCH" value="@PITCH"/>
    <set command="YAW" value="@YAW"/>

  </rc_commands>
  
  <section name="MIXER">
    <define name="AILEVON_AILERON_RATE" value="0.55"/>
    <define name="AILEVON_ELEVATOR_RATE" value="0.75"/>
  </section>

  <command_laws>
    <set servo="THR" value="@THROTTLE"/>
    <let var="aileron" value="@YAW * AILEVON_AILERON_RATE"/>
    <let var="elevator" value="@PITCH * AILEVON_ELEVATOR_RATE"/>
    <let var="rudder" value="@ROLL"/>
    <set servo="RUDDER" value="$rudder"/>
    <set servo="AILEVON_LEFT" value="$elevator - $aileron"/>
    <set servo="AILEVON_RIGHT" value="$elevator + $aileron"/>
  </command_laws>

  <section name="adc" prefix="ADC_CHANNEL_">
    <define name="IR1" value="1"/>
    <define name="IR2" value="0"/>
    <define name="VSUPPLY" value="3"/>
    <define name="IR_NB_SAMPLES" value="16"/>
  </section>
  
  <section name="AUTO1" prefix="AUTO1_">
    <define name="MAX_ROLL" value="0.8"/>
    <define name="MAX_PITCH" value="0.6"/>
  </section>

  <section name="INFRARED" prefix="IR_">
    <define name="ROLL_NEUTRAL_DEFAULT" value="-4.3" unit="deg"/>
    <define name="PITCH_NEUTRAL_DEFAULT" value="3" unit="deg"/>
    <define name="DEFAULT_CONTRAST" value="400"/>
    <define name="RAD_OF_IR_CONTRAST" value="0.6"/>
    <define name="RAD_OF_IR_MIN_VALUE" value="0.0008"/>
    <define name="RAD_OF_IR_MAX_VALUE" value="0.008"/>
<!--
    <linear name="RollOfIrs" arity="2" coeff1="-1" coeff2="-1"/>
    <linear name="PitchOfIrs" arity="2" coeff1="-1" coeff2="1"/>
-->
    <define name="RollOfIrs(i1, i2)" value="(-i1 -i2)"/>
    <define name="PitchOfIrs(i1, i2)" value="(i2-i1)"/>
    <define name="ADC_ROLL_NEUTRAL" value="-1042"/>
    <define name="ADC_PITCH_NEUTRAL" value="10"/>
  </section>

  <section name="ALT" prefix="CLIMB_">
      <define name="PITCH_PGAIN" value="-0.1"/>
    <define name="PITCH_IGAIN" value="1.0"/>
    <define name="PGAIN" value="-0.025"/>
    <define name="IGAIN" value="0.01"/>
    <define name="MAX" value="1."/>
    <define name="LEVEL_GAZ" value="0.50"/>
    <define name="GAZ_OF_CLIMB" value="0.15" unit="% / m/s"/>
    <define name="PITCH_OF_VZ_PGAIN" value="0.1"/>
  </section>
  <section name="NAV">
    <define name="COURSE_PGAIN" value="-0.2"/>
    <define name="ALTITUDE_PGAIN" value="-0.05"/>
    <define name="NAV_PITCH" value="0."/>
  </section>
  <section name="BAT">
    <define name="MILLIAMP_PER_PERCENT" value="1.24"/>
    <define name="VOLTAGE_ADC_A" value="0.01727"/>
    <define name="VOLTAGE_ADC_B" value="0.2965"/>
    <define name="VoltageOfAdc(adc)" value="(VOLTAGE_ADC_A * adc + VOLTAGE_ADC_B)"/>
    <define name="LOW_BATTERY" value="9" unit="V"/>
  </section>
  <section name="SERVOS">
    <define name="SERVOS_VOLTAGE_ADC_A" value="0.005661"/>
    <define name="SERVOS_VOLTAGE_ADC_B" value="0.014948"/>
    <define name="ServosVoltageOfAdc(adc)" value="(VOLTAGE_ADC_A * adc + VOLTAGE_ADC_B)"/>
  </section>
  <section name="MISC">
    <define name="NOMINAL_AIRSPEED" value="12."/>
    <define name="CARROT" value="5." unit="s"/>
    <define name="KILL_MODE_DISTANCE" value="(MAX_DIST_FROM_HOME*1.5)" unit="m"/>
  </section>
  <section name="SIMU">
    <define name="ROLL_RESPONSE_FACTOR" value="14."/>
    <define name="YAW_RESPONSE_FACTOR" value="1."/>
    <define name="WEIGHT" value="0.3"/>
  </section>
  <section name="FAILSAFE" prefix="FAILSAFE_">
    <define name="DELAY_WITHOUT_GPS" value="2" unit="s"/>
    <define name="DEFAULT_GAZ" value="CLIMB_LEVEL_GAZ+0.05" unit="%"/>
    <define name="DEFAULT_ROLL" value="0.17" unit="rad"/>
    <define name="DEFAULT_PITCH" value="0.08" unit="rad"/>
    <define name="HOME_RADIUS" value="50" unit="m"/>
  </section>
  <section name="CAM" prefix="CAM_">
    <define name="THETA0" value="45" unit="deg"/>
    <define name="PHI0" value="-45" unit="deg"/>
  </section>

  <section name="DATALINK" prefix="DATALINK_">
    <define name="DEVICE_TYPE" value="XBEE"/>
    <define name="DEVICE_ADDRESS" value=""/>
  </section>

   <section name="AGGRESSIVE" prefix="AGR_">
    <define name="CLIMB_GAZ" value="0.8"/><!-- Gaz for Aggressive Climb -->
    <define name="DESCENT_GAZ" value="0.1"/><!-- Gaz for Aggressive Decent -->
    <define name="CLIMB_PITCH" value="0.2"/><!-- Pitch for Aggressive Climb -->
    <define name="DESCENT_PITCH" value="-0.2"/><!-- Pitch for Aggressive Decent -->
    <define name="BLEND_START" value="15"/><!-- Altitude Error to Initiate Aggressive Climb CANNOT BE ZERO!!-->
    <define name="BLEND_END" value="8"/><!-- Altitude Error to Blend Aggressive to Regular Climb Modes  CANNOT BE ZERO!!-->
    <define name="CLIMB_NAV_RATIO" value="0.8"/><!-- Percent Navigation for Altitude Error Equal to Start Altitude -->
    <define name="DESCENT_NAV_RATIO" value="1.0"/>
    </section>

   <makefile target="sitl">
# Config for SITL simulation
include $(PAPARAZZI_SRC)/conf/autopilot/sitl.makefile
   </makefile>

   <makefile target="tunnel">
tunnel.srcs += $(SRC_ARCH)/uart_tunnel.c
   </makefile>

<makefile target="ac">
include $(PAPARAZZI_SRC)/conf/autopilot/v1_2_1.makefile
include $(PAPARAZZI_SRC)/conf/autopilot/twin_mcu_avr.makefile

# fbw.CFLAGS += -DTELEMETRY_MODE_FBW=1

ap.CFLAGS += -DDOWNLINK -DDOWNLINK_TRANSPORT=XBeeTransport
ap.srcs += downlink.c

ap.CFLAGS += -DUSE_UART0 -DDOWNLINK_AP_DEVICE=Uart0
#ap.CFLAGS += -DMODEM  -DDOWNLINK_AP_DEVICE=Modem
#ap.srcs += $(SRC_ARCH)/modem_hw.c 

#ap.CFLAGS += -DRADIO_CONTROL_CALIB
#ap.srcs += rc_settings.c

ap.CFLAGS += -DRADIO_CONTROL_TYPE=RC_FUTABA
#just added radio line from romans text

ap.CFLAGS += -DDATALINK=XBEE
ap.srcs += traffic_info.c datalink.c xbee.c
ap.CFLAGS += -DXBEE_UART=Uart0 -DUART0_BAUD=B9600
</makefile>

</airframe>
